apiVersion: v1
kind: Pod
metadata:
  name: prometheus-apache
  annotations:
    ad.datadoghq.com/prometheus-apache.check_names: '["openmetrics"]'
    ad.datadoghq.com/prometheus-apache.init_configs: '[{}]'
    ad.datadoghq.com/prometheus-apache.instances: |
            [
              {
                "prometheus_url": "http://%%host%%:%%port%%/metrics",
                "namespace": "apache",
                "metrics": [
                {"*"}
                ]
              }
            ]    
spec:
  containers:
    - name: prometheus-apache
      image: prom/prometheus
      ports: 
        - containerPort: 9117

---
kind: Service
apiVersion: v1
metadata:
  name: pa-service
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9117
      targetPort: 9117
    
    