# docker run -it --rm --name test -p 80:5050 -e APP_ENV aldrickdev/pykube:0.1.3
version: "3.8"

services:
  pykube:
    image: aldrickdev/pykube:$APP_VERSION
    ports:
      - 80:5050
    env_file: .env